lang: en-US

destination: ./build

plugins:
  - jekyll-include-cache
  - jekyll-assets

exclude:
  - Rakefile
  - Gemfile*
  - node_modules
  - vendor

collections:
   pages:
     output: true
     permalink: /:path

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .jekyll-cache/assets
  cache_type: filesystem
  prefix: "/assets"
  assets:
    - "*.css"
    - "*.js"
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
  features:
    liquid: false
    integrity: true
